version: "3"

services:
  app-push-api:
    image: "big-trader-docker-registry.kr.ncr.ntruss.com/app-push-api"
    ports:
      - "9090:9090"
    environment:
      TZ: Asia/Seoul
      SPRING_PROFILES_ACTIVE: prod
      JASYPT_ENCRYPTOR_PASSWORD: ${JASYPT_ENCRYPTOR_PASSWORD}
