name: big-trader-ci-cd

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: prepare gradle build
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew big-trader-api:build

      - name: Login to Cotainer Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.BIGTRADER_DOCKER_REGISTRY }}
          username: ${{ secrets.BIGTRADER_ACCESS_KEY }}
          password: ${{ secrets.BIGTRADER_SECRET_KEY }}

      - name: Jib container publish
        run: ./gradelw :big-trader-api:jib

      - name: move big-trader-api-dir
        run: cd ./big-trader-api/

      - name: make docker compose env file
        run: |
          pwd
          echo ${{ secrets.BIGTRAER_ENV_FILE }} > ./.env

      - name: Deploy to Docker swarm
        uses: pcjun97/action-setup-docker-host-ssh@v1
        with:
          host: ${{ secrets.BIGTRAER_REMOTE_DOCKER_HOST }}
          user: ${{ secrets.BIGTRAER_SSH_USER }}
          key: ${{ secrets.BIGTRAER_DOCKER_SSH_PRIVATE_KEY }}
      - run: |
          docker login -u ${{ secrets.BIGTRADER_ACCESS_KEY }} ${{ secrets.BIGTRADER_DOCKER_REGISTRY }} -p ${{ secrets.BIGTRADER_SECRET_KEY }}

          docker ps -qa

          docker rm -f $(docker ps -qa)
          docker image rm -f $(docker image ls -q)
          docker-compose -f docker-compose-prod.yml up -d
