name: big-trader-ci-cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Cotainer Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.BIGTRADER_DOCKER_REGISTRY }}
          username: ${{ secrets.BIGTRADER_ACCESS_KEY }}
          password: ${{ secrets.BIGTRADER_SECRET_KEY }}


      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.BIGTRADER_DOCKER_REGISTRY }}/action-test:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: connect ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BIGTRADER_HOST_IP }}
          username: ${{ secrets.BIGTRADER_HOST_USER }}
          key: ${{ secrets.BIGTRADER_PEM_KEY }}
          port: ${{ secrets.BIGTRADER_PORT }}
          script: |
            docker login -u ${{ secrets.BIGTRADER_ACCESS_KEY }} ${{ secrets.BIGTRADER_DOCKER_REGISTRY }} -p ${{ secrets.BIGTRADER_SECRET_KEY }}
            
            docker pull ${{ secrets.BIGTRADER_DOCKER_REGISTRY }}/big-trader-api:latest
            
            docker run -d --name big-trader-api -p 8081:8080 ${{ secrets.BIGTRADER_DOCKER_REGISTRY }}/big-trader-api
            
            exit
