name: big-trader-cd

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: make docker compose env file
        run: |
          pwd
          echo ${{ secrets.BIGTRADER_ENV_FILE }} > ./big-trader-api/.env

      - name: Deploy Docker image on server
        uses: pcjun97/action-setup-docker-host-ssh@v1
        with:
          host: ${{ secrets.BIGTRADER_REMOTE_DOCKER_HOST }}
          user: ${{ secrets.BIGTRADER_SSH_USER }}
          key: ${{ secrets.BIGTRADER_DOCKER_SSH_PRIVATE_KEY }}
      - run: |
          docker login -u ${{ secrets.BIGTRADER_ACCESS_KEY }} ${{ secrets.BIGTRADER_DOCKER_REGISTRY }} -p ${{ secrets.BIGTRADER_SECRET_KEY }}

          docker-compose -f ./big-trader-api/docker-compose-prod.yml down
          
          docker-compose -f ./big-trader-api/docker-compose-prod.yml up -d
