name: execute test on pr

on:
  pull_request:
    branches:
      - main
jobs:
  big-trader-api-test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: prepare gradle test
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: execute test
        run: ./gradlew big-trader-api:test

      - name: execute build
        run: ./gradlew big-trader-api:build -x test

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.BIGTRADER_DOCKER_REGISTRY }}
          username: ${{ secrets.BIGTRADER_ACCESS_KEY }}
          password: ${{ secrets.BIGTRADER_SECRET_KEY }}

      - name: Jib container publish
        run: ./gradlew :big-trader-api:jib

  app-push-api-test-and-build:
    needs: big-trader-api-test-and-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: prepare gradle test
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: execute test
        run: ./gradlew app-push-api:test

      - name: execute build
        run: ./gradlew app-push-api:build -x test

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.APP_PUSH_API_DOCKER_REGISTRY }}
          username: ${{ secrets.APP_PUSH_API_ACCESS_KEY }}
          password: ${{ secrets.APP_PUSH_API_SECRET_KEY }}

      - name: Jib container publish
        run: ./gradlew :app-push-api:jib
