name: execute test on pr

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: prepare gradle test
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: execute test
        run: ./gradlew test
